//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopApp_4ISIP322
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int TotalProducts { get; set; }
        public decimal AveragePrice { get; set; }
        public decimal TotalValue { get; set; }
    }
}
